esphome:
  name: hydroponics2024
  includes: 
    - calcfunctions.h

esp8266:
  board: d1_mini
#  restore_from_flash: true  


packages:
  sensors: !include sensors.yaml
  actuators: !include actuators.yaml
  calculations: !include calculations.yaml
  #mqttsend: !include mqttsend.yaml



mqtt:
  broker: !secret mqtt_broker
  port: 1883
  id: "mq"
 
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

time:
  - platform: sntp
    id: sntp_time
    servers: 
      - 116.203.244.102
      -  90.187.112.137

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hydroponics2024 Fallback Hotspot"
    password: !secret fallbackpass

captive_portal:
    

