dallas:
  - pin: D7
    update_interval: 30s

sensor:
  # Blue
  - platform: dallas
    name: "Air temperature"
    id: air
    address:  0xb848311e1e64ff28
    resolution: 12
    filters:
    - filter_out: nan

  # Red
  - platform: dallas
    name: "Water temperature"
    id: water
    address:  0x1b7a2d1e1e64ff28
    resolution: 12
    filters:
    - filter_out: nan

  # yellow
  - platform: dallas
    name: "Buffer water temperature"
    id: buffer
    address:  0xa7383b1e1e64ff28
    resolution: 12
    filters:
    - filter_out: nan

  # Black
  - platform: dallas
    name: "Solar temperature"
    id: solar
    address:  0x4800000696733828
    resolution: 12
    filters:
    - filter_out: nan


  - platform: adc
    pin: A0
    name: "EC Sensor"
    id: ecSensor
    accuracy_decimals: 3
    # Updates are controlled by an interval which controls
    # The power supply as well
    update_interval: never
    filters:
      - exponential_moving_average:
          alpha: 0.02
          send_every: 1
      - lambda: "return fertilizer(x);"